#!/usr/bin/env bash
ros2 topic pub --once /trigger_start std_msgs/msg/Empty "{}"
# ros2 service call /snc_exploration_control snc_interfaces/srv/ExplorationControl "{command: 'r'}"

# ros2 topic pub --once /snc_start std_msgs/msg/Empty "{}"
# ros2 service call /snc_exploration_control snc_interfaces/srv/ExplorationControl "{command: 'START'}"
